version: "3"
services:

  vprodb:
    image: ozunuane/vprodb:V1
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      -  MYSQL_ROOT_PASSWORD="admin123"


  vpromch:
    image: memcached
    ports:
      - "11211:11211"
    
  vprormq:
    image: rabbitmq
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=test 

  vproapp:
    image: ozunuane/vproapp:V1
    ports:
      - "8080:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapps


  vproweb:
    image: ozunuane/vproaweb:V1
    ports:
      - "80:80"




volumes:
  vprodbdata: {}  
  vproappdata: {}  

