version: "3.9"
services:

  vprodb:
    image: ozunuane/vprodb:v1
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      -  MYSQL_ROOT_PASSWORD="admin123"

  vpromch:
    image: memcached
    ports:
      - "11211:11211"
    
  vprormq:
    image: vprormq
    ports:
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=test

  




volumes:
  vprodbdata: {}  
